# Generated by Django 5.2.5 on 2025-09-03 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("week", models.PositiveIntegerField()),
                ("date", models.DateField()),
                (
                    "course_semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="lms_courses.coursesemester",
                    ),
                ),
            ],
            options={
                "ordering": ["week"],
            },
        ),
        migrations.CreateModel(
            name="LabReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("max_grade", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report",
                        to="lms_courses.labsession",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="labsession",
            constraint=models.UniqueConstraint(
                fields=("course_semester", "name", "week"), name="uniq_week_per_lab"
            ),
        ),
    ]
