# Generated by Django 5.2.5 on 2025-09-04 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_courses", "0002_labsession_labreport_labsession_uniq_week_per_lab"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("present", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="lms_courses.labsession",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["student__username"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "student"), name="uniq_participation_per_session_student"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LabReportGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("grade", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "lab_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="lms_courses.labreport",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_report_grades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["student__username"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lab_report", "student"), name="uniq_grade_per_report_student"
                    )
                ],
            },
        ),
    ]
