# Generated by Django 5.2.5 on 2025-09-04 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms_courses", "0003_labparticipation_labreportgrade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("max_grade", models.PositiveIntegerField()),
                ("due_date", models.DateField()),
                (
                    "course_semester",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_assignment",
                        to="lms_courses.coursesemester",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="FinalAssignmentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("submitted", models.BooleanField(default=False)),
                ("grade", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "final_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="lms_courses.finalassignment",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_assignment_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["student__username"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("final_assignment", "student"),
                        name="uniq_final_assignment_result_per_student",
                    )
                ],
            },
        ),
    ]
