[tool.flake8]
max-line-length = 100
extend-ignore = ["E203","W503"]
per-file-ignores = ["**/migrations/*.py:E501"]

[tool.black]
line-length = 100
target-version = ["py313"]

[tool.isort]
profile = "black"
line_length = 100
